Add option to show/hide Templater ribbon icon
SilentVoid13/Templater pull request #653
Opened 2022-05-30 16:48 UTC by fmbarina

Enhancement #647 I suggested recently.

Add a plugin option to show or hide the sidebar/ribbon icon. There are other ways, including even [another obsidian extension](https://github.com/phibr0/obsidian-customizable-sidebar) with an option to hide the Templater icon. I think it makes more sense and is better for the extension itself to offer that option.

Changes Made:
- Added boolean setting enable_ribbon_icon, default true, toggle option hides/shows icon.
- Added check to see if setting is true before adding icon in main.

2022-09-01 14:13 UTC, shabegom requested changes
just needs one small language tweak

2022-09-01 14:13 UTC, shabegom commented on src/settings/Settings.ts
> +            "Show Templater ribbon icon in sidebar, allowing you to quickly use templates anywhere."
Show Templater icon in sidebar ribbon, allowing you to quickly use templates anywhere.

2022-09-01 23:56 UTC, fmbarina commented
Thanks, changed. Really makes me wonder if I can truly call myself fluent.
Squashed into a single commit so that it fits better in the commit history. I think that's how you're supposed to do it?

2022-09-02 00:43 UTC, shabegom commented
Sweet, thanks! Will merge and add to next release

2022-09-02 00:43 UTC, merged