Updating examples to clarify and simplify
SilentVoid13/Templater pull request #667
Opened 2022-06-18 06:49 UTC by patrickkelso

I spent a lot of time trying to figure out the syntax for using throw_on_cancel because there was no example added when the feature was. 

I've also updated the examples so each one explains a little of what it does making it easier to identify a use case. I think this will make the documentation a lot more accessible to non programmers.

2022-06-18 07:40 UTC, AB1908 commented
Hey while you're on this, can you modify the docs to make the examples be part of the function's section instead of being jumbled together at the end?

2022-09-01 13:52 UTC, shabegom commented
The docs should be generated on release. @patrickkelso please add these examples to the `documentation.toml` file under the appropriate header. example:

```
[tp.system.functions.prompt]
name = "prompt"
description = "Spawns a prompt modal and returns the user's input."
definition = "tp.system.prompt(prompt_text?: string, default_value?: string, throw_on_cancel: boolean = false)"
example = "<% tp.system.prompt("Please enter a value") %>"
```

2022-09-01 14:15 UTC, shabegom requested changes
Move examples under appropriate functions in documentation.toml

2022-09-01 19:57 UTC, patrickkelso commented
Understood. I'll update asap.

2024-03-09 03:28 UTC, Zachatoo commented
Doing some cleanup, please reopen if you'd still like to contribute!

2024-03-09 03:28 UTC, closed without merging