Feature: multiline input with `tp.system.prompt`
SilentVoid13/Templater pull request #697
Opened 2022-07-18 12:18 UTC by AB1908

I've added a new multi-line input prompt inspired by chhoumann/QuickAdd. See [here](https://github.com/chhoumann/quickadd/blob/master/src/gui/GenericWideInputPrompt/GenericWideInputPrompt.ts) for original.

It can be invoked using
```js
let default_value = "Original";
let prompt_text = "Prompt Title Here";
let throw_on_cancel = false;
let multi_line = true;
tR += await tp.system.prompt(prompt_text, default_value, throw_on_cancel, multi_line);
```

This is an optional variable that shouldn't introduce any breaking changes. I haven't had a chance to test this on mobile.

Note: the event handler for mobile behaves slightly differently. For multi-line inputs, the Submit button must be used as the enter key moves the cursor to the next line.

Please let me know if there's any cleanup I should do.

2022-07-18 12:41 UTC, AB1908 commented
If anyone needs this, feel free to install 1.13.0 from my fork via BRAT.

2022-09-01 13:33 UTC, shabegom commented on manifest.json
> +    "version": "1.13.0",
don't update the version number in a feature PR, we'll do that when cutting a new release candidate. remove this from the PR.

2022-09-01 14:15 UTC, shabegom requested changes
remove manifest.json

2022-09-02 06:44 UTC, AB1908 commented
I did that for the brat thing. I'll split that off into a separate branch next time.

2022-09-02 11:33 UTC, shabegom approved these changes

2022-09-02 11:33 UTC, merged